gText_Birch_Welcome::
	.string "Salut! Scuze pentru înârziere.\p"
	.string "Bun venit în lumea POKEMONILOR!\p"
	.string "Numele meu este BIRCH.\p"
	.string "Dar toată lumea mă strigă PROFESORUL \n"
	.string "DE POKEMONI.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Acesta este un “POKEMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "În fiecare colț al acestei lumi regăsim\n"
	.string "creaturi numite POKEMONI.\p"
	.string "Noi oamenii trăim alături de POKEMONI,\n"
	.string "uneori ca parteneri de joacă, și\l"
	.string "uneori ca și colegi de muncă.\p"
	.string "Și uneori, formăm o echipă\n"
	.string "și luptăm cu alții ca și noi.\p"
	.string "Dar totuși în ciuda relației strânse\n"
	.string "nu cunoaștem tot despre POKEMONI.\p"
	.string "Defapt sunt o sumedenie de \n"
	.string "secrete în ceea ce privește POKEMONII.\p"
	.string "Pentru a le descoperii secretele,\n"
	.string "Am început să îi studiez.\l"
	.string "Cu asta mă ocup.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Deci tu ai fi?$"

gText_Birch_BoyOrGirl::
	.string "Ești un băiat?\n"
	.string "Sau ești o fată?$"

gText_Birch_WhatsYourName::
	.string "În regulă.\n"
	.string "Cum te numești?$"

gText_Birch_SoItsPlayer::
	.string "Deci te numești {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, bine!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
