gText_Birch_Welcome::
	.string "Salut! Scuze pentru întârziere.\p"
	.string "Bun venit în lumea POKEMONILOR!\p"
	.string "Numele meu este BIRCH.\p"
	.string "Dar toată lumea mă strigă PROFESORUL \n"
	.string "DE POKEMONI.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Acesta este un POKEMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "În fiecare colț al acestei lumi regăsim\n"
	.string "creaturi numite POKEMONI.\p"
	.string "Noi oamenii trăim alături de POKEMONI,\n"
	.string "uneori ca parteneri de joacă, și\l"
	.string "uneori ca și colegi de muncă.\p"
	.string "Și uneori, formăm o echipă\n"
	.string "și luptăm cu alții ca și noi.\p"
	.string "Dar totuși în ciuda relației noastre strânse\n"
	.string "nu cunoaștem totul despre POKEMONI.\p"
	.string "De fapt sunt o sumedenie de \n"
	.string "secrete în ceea ce privește POKEMONII.\p"
	.string "Pentru a le descoperi secretele,\n"
	.string "Am început să îi studiez.\l"
	.string "Cu asta mă ocup.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Deci tu ai fi?$"

gText_Birch_BoyOrGirl::
	.string "Ești un băiat?\n"
	.string "Sau ești o fată?$"

gText_Birch_WhatsYourName::
	.string "În regulă.\n"
	.string "Cum te numești?$"

gText_Birch_SoItsPlayer::
	.string "Deci te numești {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, bine!\p"
	.string "Tu ești {GEN}cel{GEN_SEP}cea{GEN_END} care se va muta\n"
	.string "în orășelul de unde sunt eu: Rădăcinești.\l"
	.string "Înțeleg acum!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "În regulă, ești gata?\p"
	.string "Propria ta aventură va începe chiar\l"
	.string "acum.\p"
	.string "Fi {GEN}curajos{GEN_SEP}curajoasă{GEN_END} căci ești pe cale să pătrunzi\n"
	.string "în lumea POKEMONILOR unde vise,\l"
	.string "aventură, și multe prietenii te așteaptă!\p"
	.string "Ei bine, te voi aștepta.\n"
	.string "Vino să mă vizitezi în LABORATORUL meu\l"
	.string "de POKEMONI.\p"
	.string "$"
